ALTER TABLE account_ledgers
ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD COLUMN updated_at TIMESTAMPTZ,
ADD COLUMN deleted_at TIMESTAMPTZ,
ADD COLUMN updated_by BIGINT,
ADD COLUMN deleted_by BIGINT,
ADD COLUMN created_by BIGINT;